Bumper til dekorator V2.0.0
navikt/sykepengesoknad-frontend pull request #1338
Opened 2023-04-26 12:31 UTC by golshidb93

2023-04-26 12:54 UTC, heyvard approved these changes
🦶

2023-04-27 07:08 UTC, heyvard requested changes

2023-04-27 07:08 UTC, heyvard commented on nais/app/demo.yaml
>          - host: www.nav.no
denne kan fjernes nå takfisk

2023-04-27 07:08 UTC, heyvard requested changes

2023-04-27 07:08 UTC, heyvard commented on nais/app/naiserator.yaml
>          - host: www.nav.no                      # for prod
kan fjernes

2023-04-27 12:35 UTC, kulsveen approved these changes

2023-04-27 12:44 UTC, heyvard approved these changes

2023-04-27 13:17 UTC, merged