Renamer amplitude events og legger til en måling på spørsmål åpnet
navikt/sykepengesoknad-frontend pull request #1503
Opened 2023-05-30 13:13 UTC by golshidb93

2023-05-30 17:21 UTC, heyvard requested changes

2023-05-30 17:21 UTC, heyvard commented on src/components/sporsmal/sporsmal-form/sporsmal-form.tsx
> -                spørsmål: sporsmal.tag,
hmm, kanskje den forstatt bør være spørsmål 🤔  https://github.com/navikt/analytics-taxonomy/tree/main/events/skjema%20sp%C3%B8rsm%C3%A5l%20besvart

2023-05-31 06:23 UTC, golshidb93 commented on src/components/sporsmal/sporsmal-form/sporsmal-form.tsx
> -                spørsmål: sporsmal.tag,
👍

2023-05-31 06:25 UTC, heyvard approved these changes

2023-05-31 06:25 UTC, merged